
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ima_rent_a_car_system
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

jwt:
  secret: your-super-secret-jwt-key
  expirationMs: 86400000

# Hardcoded user credentials (for admin and data-entry)
users:
  - username: admin
    password: admin123
    role: ADMIN
  - username: dataentry
    password: data123
    role: DATA_ENTRY

